// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WEBSITEDIENTHOAI.Data;

#nullable disable

namespace WEBSITEDIENTHOAI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("WEBSITEDIENTHOAI.Models.CTHOADON", b =>
                {
                    b.Property<int>("Idcthd")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Idcthd"), 1L, 1);

                    b.Property<string>("Idhoadon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Ngaythanhtoan")
                        .HasColumnType("datetime2");

                    b.HasKey("Idcthd");

                    b.ToTable("CTHOADON");
                });

            modelBuilder.Entity("WEBSITEDIENTHOAI.Models.CTSANPHAM", b =>
                {
                    b.Property<int>("IDCTSP")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDCTSP"), 1L, 1);

                    b.Property<int>("Idsp")
                        .HasColumnType("int");

                    b.Property<string>("Tensp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThuongHieu")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IDCTSP");

                    b.ToTable("CTSANPHAM");
                });

            modelBuilder.Entity("WEBSITEDIENTHOAI.Models.GIOHANG", b =>
                {
                    b.Property<int>("IdGiohang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdGiohang"), 1L, 1);

                    b.Property<int?>("Idsp")
                        .HasColumnType("int");

                    b.Property<int?>("Sluongdat")
                        .HasColumnType("int");

                    b.Property<string>("Tensp")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdGiohang");

                    b.ToTable("GIOHANG");
                });

            modelBuilder.Entity("WEBSITEDIENTHOAI.Models.HOADON", b =>
                {
                    b.Property<int>("Idhoadon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Idhoadon"), 1L, 1);

                    b.Property<int?>("IdGiohang")
                        .HasColumnType("int");

                    b.Property<int?>("Sluongdat")
                        .HasColumnType("int");

                    b.Property<float?>("Tongdonhang")
                        .HasColumnType("real");

                    b.HasKey("Idhoadon");

                    b.ToTable("HOADON");
                });

            modelBuilder.Entity("WEBSITEDIENTHOAI.Models.MAUSAC", b =>
                {
                    b.Property<int>("Idcl")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Idcl"), 1L, 1);

                    b.Property<int>("Idctsp")
                        .HasColumnType("int");

                    b.Property<int>("Soluong")
                        .HasColumnType("int");

                    b.Property<string>("Tenms")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Idcl");

                    b.ToTable("MAUSAC");
                });

            modelBuilder.Entity("WEBSITEDIENTHOAI.Models.SANPHAM", b =>
                {
                    b.Property<int>("Idsp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Idsp"), 1L, 1);

                    b.Property<float?>("Giasp")
                        .HasColumnType("real");

                    b.Property<int?>("Sluong")
                        .HasColumnType("int");

                    b.Property<string>("Tensp")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Idsp");

                    b.ToTable("SANPHAM");
                });
#pragma warning restore 612, 618
        }
    }
}
